version: "3"

services:
  # Banco de dados usuarios
  pg_guia_fontes:
    image: "postgres:13.3-alpine"
    container_name: pg_guia_fontes
    tty: true
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - "POSTGRES_DB=${POSTGRESS_DATABASE}"
      - "POSTGRES_USER=${POSTGRESS_USER}"
      - "POSTGRES_PASSWORD=${POSTGRESS_PASSWORD}"
    networks:
      - guia_fontes

  # Banco com os dados de lattes
  es_guia_fontes:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
    container_name: es_guia_fontes
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - ELASTIC_PASSWORD=$ELASTIC_PASSWORD
      - xpack.security.enabled=true
      - xpack.security.authc.api_key.enabled=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - guia_fontes

volumes:
  pg_data:
    name: guia_fontes_pg_data
  elastic_data:
    name: guia_fontes_elastic_data

networks:
  guia_fontes:
    name: 'guia_fontes'
    driver: 'bridge'
